const CobStatusList = {
  ACTIVE: 'ACTIVE',
  CONCLUDED: 'CONCLUDED',
  REFUNDED: 'REFUNDED',
  REFUND_PROCESSING: 'REFUND_PROCESSING',
  REFUND_NOT_DONE: 'REFUND_NOT_DONE',
  REMOVED_BY_USER: 'REMOVED_BY_USER',
  REMOVED_BY_PSP: 'REMOVED_BY_PSP',
  EXPIRED: 'EXPIRED'
} as const;

export { CobStatusList };
